const $=s=>document.querySelector(s);
const clamp=(v,min=0,max=99)=>Math.max(min,Math.min(max,v));
const SAVE_KEY='football-career-v2';

const crestSlug=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(fc|cf|afc|ac|sc|sfc|cfc|calcio|football club)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim().replace(/ /g,'-');
const C=(name,abbr,league,power,color,style,query)=>({name,abbr,league,power,color,style,query,crest:`assets/crests-v2/${crestSlug(query)}.webp`});
const CLUBS=[
 ['阿森纳','ARS','英超',88,'#d92332','attack','Arsenal FC'],['阿斯顿维拉','AVL','英超',84,'#7a244b','attack','Aston Villa FC'],['伯恩茅斯','BOU','英超',78,'#c8202f','physical','AFC Bournemouth'],['布伦特福德','BRE','英超',78,'#d61f2c','physical','Brentford FC'],['布莱顿','BHA','英超',80,'#2374c6','youth','Brighton & Hove Albion FC'],['伯恩利','BUR','英超',72,'#6e1b46','physical','Burnley FC'],['切尔西','CHE','英超',86,'#16469d','youth','Chelsea FC'],['水晶宫','CRY','英超',81,'#1b4a9e','physical','Crystal Palace FC'],['埃弗顿','EVE','英超',78,'#244e9b','physical','Everton FC'],['富勒姆','FUL','英超',79,'#202020','attack','Fulham FC'],['利兹联','LEE','英超',74,'#1d5aa7','physical','Leeds United FC'],['利物浦','LIV','英超',90,'#be1e2d','physical','Liverpool FC'],['曼城','MCI','英超',92,'#69aee7','attack','Manchester City FC'],['曼联','MUN','英超',84,'#c8202f','star','Manchester United FC'],['纽卡斯尔联','NEW','英超',85,'#222222','physical','Newcastle United FC'],['诺丁汉森林','NFO','英超',81,'#d51f2b','physical','Nottingham Forest FC'],['桑德兰','SUN','英超',73,'#d82032','youth','Sunderland AFC'],['热刺','TOT','英超',83,'#15264b','attack','Tottenham Hotspur FC'],['西汉姆联','WHU','英超',78,'#7a263a','physical','West Ham United FC'],['狼队','WOL','英超',77,'#d99d19','physical','Wolverhampton Wanderers FC'],
 ['毕尔巴鄂竞技','ATH','西甲',84,'#c52232','physical','Athletic Bilbao'],['马德里竞技','ATM','西甲',87,'#c62939','physical','Atletico Madrid'],['奥萨苏纳','OSA','西甲',78,'#a51e2f','physical','CA Osasuna'],['塞尔塔','CEL','西甲',79,'#69a7dd','attack','Celta Vigo'],['阿拉维斯','ALA','西甲',74,'#17589a','physical','Deportivo Alaves'],['巴塞罗那','BAR','西甲',92,'#263a85','youth','FC Barcelona'],['皇家贝蒂斯','BET','西甲',82,'#208a55','attack','Real Betis'],['埃尔切','ELC','西甲',71,'#2c9a58','physical','Elche CF'],['西班牙人','ESP','西甲',75,'#3186c8','physical','RCD Espanyol'],['赫塔费','GET','西甲',77,'#23529b','physical','Getafe CF'],['赫罗纳','GIR','西甲',80,'#cf2838','attack','Girona FC'],['莱万特','LEV','西甲',71,'#a23b62','attack','Levante UD'],['马略卡','MLL','西甲',77,'#c93439','physical','RCD Mallorca'],['巴列卡诺','RAY','西甲',76,'#d92835','physical','Rayo Vallecano'],['皇家马德里','RMA','西甲',94,'#b6a56a','star','Real Madrid CF'],['皇家奥维耶多','OVI','西甲',71,'#2454a2','physical','Real Oviedo'],['皇家社会','RSO','西甲',82,'#2b7dbb','youth','Real Sociedad'],['塞维利亚','SEV','西甲',79,'#c92a38','star','Sevilla FC'],['瓦伦西亚','VAL','西甲',78,'#e19327','youth','Valencia CF'],['比利亚雷亚尔','VIL','西甲',83,'#d5b91f','attack','Villarreal CF'],
 ['亚特兰大','ATA','意甲',85,'#2455a4','attack','Atalanta BC'],['博洛尼亚','BOL','意甲',82,'#9d2439','physical','Bologna FC'],['卡利亚里','CAG','意甲',74,'#9d2439','physical','Cagliari Calcio'],['科莫','COM','意甲',80,'#2460a5','attack','Como 1907'],['克雷莫内塞','CRE','意甲',70,'#b12735','physical','US Cremonese'],['佛罗伦萨','FIO','意甲',82,'#63358d','attack','ACF Fiorentina'],['热那亚','GEN','意甲',76,'#9f243a','physical','Genoa CFC'],['国际米兰','INT','意甲',89,'#16439b','physical','Inter Milan'],['尤文图斯','JUV','意甲',85,'#242424','physical','Juventus FC'],['拉齐奥','LAZ','意甲',82,'#66a3d8','attack','SS Lazio'],['莱切','LEC','意甲',73,'#d3a921','physical','US Lecce'],['AC米兰','ACM','意甲',86,'#b31f2b','star','AC Milan'],['那不勒斯','NAP','意甲',86,'#2b91c8','attack','SSC Napoli'],['帕尔马','PAR','意甲',75,'#e2b72c','youth','Parma Calcio 1913'],['比萨','PIS','意甲',70,'#214c92','physical','Pisa SC'],['罗马','ROM','意甲',83,'#8f1837','physical','AS Roma'],['萨索洛','SAS','意甲',75,'#15955d','attack','US Sassuolo'],['都灵','TOR','意甲',78,'#7e283a','physical','Torino FC'],['乌迪内斯','UDI','意甲',76,'#313131','youth','Udinese Calcio'],['维罗纳','VER','意甲',73,'#244f91','physical','Hellas Verona FC'],
 ['奥格斯堡','AUG','德甲',74,'#a92431','physical','FC Augsburg'],['柏林联合','FCU','德甲',76,'#d12431','physical','Union Berlin'],['不莱梅','SVW','德甲',77,'#168b59','attack','Werder Bremen'],['多特蒙德','BVB','德甲',85,'#d2b900','youth','Borussia Dortmund'],['法兰克福','SGE','德甲',84,'#bd2632','attack','Eintracht Frankfurt'],['弗赖堡','SCF','德甲',79,'#c72b39','physical','SC Freiburg'],['汉堡','HSV','德甲',74,'#285b9d','star','Hamburger SV'],['海登海姆','FCH','德甲',72,'#24589d','physical','FC Heidenheim'],['霍芬海姆','TSG','德甲',76,'#2670b8','youth','TSG 1899 Hoffenheim'],['科隆','KOE','德甲',74,'#cf2937','star','FC Koln'],['莱比锡','RBL','德甲',84,'#d32b3d','youth','RB Leipzig'],['勒沃库森','B04','德甲',87,'#b7192b','attack','Bayer Leverkusen'],['拜仁','FCB','德甲',92,'#c81e42','star','Bayern Munich'],['美因茨','M05','德甲',78,'#c92737','physical','Mainz 05'],['门兴','BMG','德甲',79,'#202020','attack','Borussia Monchengladbach'],['圣保利','STP','德甲',73,'#5c3427','physical','FC St Pauli'],['斯图加特','VFB','德甲',84,'#d22435','attack','VfB Stuttgart'],['沃尔夫斯堡','WOB','德甲',78,'#4c9c47','physical','VfL Wolfsburg'],
 ['昂热','SCO','法甲',72,'#202020','physical','Angers SCO'],['欧塞尔','AJA','法甲',74,'#2661a6','youth','AJ Auxerre'],['布雷斯特','SB29','法甲',78,'#cc2635','physical','Stade Brestois 29'],['勒阿弗尔','HAC','法甲',72,'#6e9ed0','physical','Le Havre AC'],['朗斯','RCL','法甲',81,'#c72c36','physical','RC Lens'],['里尔','LOSC','法甲',83,'#c92738','youth','Lille OSC'],['洛里昂','FCL','法甲',72,'#e58232','attack','FC Lorient'],['里昂','OL','法甲',80,'#1f4f9f','youth','Olympique Lyonnais'],['马赛','OM','法甲',83,'#199bd8','physical','Olympique Marseille'],['梅斯','FCM','法甲',71,'#8e243d','physical','FC Metz'],['摩纳哥','ASM','法甲',84,'#d02c3c','youth','AS Monaco'],['南特','FCN','法甲',74,'#d2bd24','youth','FC Nantes'],['尼斯','OGCN','法甲',81,'#bb2633','physical','OGC Nice'],['巴黎FC','PFC','法甲',73,'#244c8c','youth','Paris FC'],['巴黎圣日耳曼','PSG','法甲',92,'#172b55','star','Paris Saint-Germain'],['雷恩','SRFC','法甲',80,'#c32936','youth','Stade Rennais FC'],['斯特拉斯堡','RCSA','法甲',80,'#2e72b7','youth','RC Strasbourg Alsace'],['图卢兹','TFC','法甲',77,'#6d3a8b','attack','Toulouse FC'],
 ['本菲卡','SLB','葡超',82,'#d9272e','attack','SL Benfica'],['葡萄牙体育','SCP','葡超',84,'#168653','youth','Sporting CP'],['波尔图','FCP','葡超',82,'#2363a6','physical','FC Porto'],['布拉加','SCB','葡超',78,'#c92a39','attack','SC Braga'],['阿贾克斯','AJA','荷甲',80,'#d51f2b','youth','AFC Ajax'],['埃因霍温','PSV','荷甲',83,'#d72737','attack','PSV Eindhoven'],['费耶诺德','FEY','荷甲',82,'#c52937','physical','Feyenoord'],['阿尔克马尔','AZ','荷甲',78,'#c92331','youth','AZ Alkmaar'],
 ['河床','CARP','阿甲',81,'#d82035','attack','River Plate'],['博卡青年','BOC','阿甲',80,'#214d91','physical','Boca Juniors'],['竞技俱乐部','RAC','阿甲',76,'#62a9df','youth','Racing Club'],['独立竞技','IND','阿甲',75,'#c82935','physical','Independiente'],
 ['弗拉门戈','FLA','巴甲',83,'#c22534','star','Flamengo'],['帕尔梅拉斯','PAL','巴甲',83,'#198250','physical','Palmeiras'],['桑托斯','SAN','巴甲',76,'#303030','youth','Santos FC'],['圣保罗','SAO','巴甲',78,'#c52b38','youth','Sao Paulo FC'],
 ['迈阿密国际','MIA','美职联',76,'#dc5b83','star','Inter Miami CF'],['洛杉矶FC','LAFC','美职联',75,'#b79a54','attack','Los Angeles FC'],['西雅图海湾人','SEA','美职联',75,'#4b9d4a','physical','Seattle Sounders FC'],
 ['利雅得胜利','NAS','沙特联',80,'#d8bd22','star','Al Nassr FC'],['利雅得新月','HIL','沙特联',83,'#2765af','star','Al Hilal SFC'],['吉达联合','ITT','沙特联',79,'#202020','physical','Al Ittihad Club'],
 ['凯尔特人','CEL','苏超',78,'#198750','physical','Celtic FC'],['流浪者','RAN','苏超',77,'#26529b','physical','Rangers FC'],['阿伯丁','ABE','苏超',70,'#c82935','youth','Aberdeen FC'],
 ['加拉塔萨雷','GAL','土超',81,'#c93239','star','Galatasaray SK'],['费内巴切','FEN','土超',80,'#d6bd24','attack','Fenerbahce SK'],['贝西克塔斯','BJK','土超',77,'#222222','physical','Besiktas JK'],
 ['上海海港','SIPG','中超',73,'#c92632','attack','Shanghai Port FC'],['上海申花','SHS','中超',72,'#2670ba','physical','Shanghai Shenhua FC'],['山东泰山','SHT','中超',72,'#e5812f','youth','Shandong Taishan FC'],['北京国安','BGR','中超',71,'#4b9c45','youth','Beijing Guoan FC'],
 ['圣彼得堡泽尼特','ZEN','俄超',79,'#2588c9','star','Zenit Saint Petersburg'],['莫斯科中央陆军','CSK','俄超',76,'#c72737','physical','CSKA Moscow'],['莫斯科斯巴达','SPA','俄超',75,'#d12b3b','attack','Spartak Moscow'],['莫斯科迪纳摩','DYN','俄超',74,'#2670b8','youth','Dynamo Moscow'],
 ['布鲁日','CLU','比甲',78,'#2358a3','physical','Club Brugge KV'],['安德莱赫特','AND','比甲',76,'#633994','youth','RSC Anderlecht'],['亨克','GNK','比甲',75,'#2759a0','youth','KRC Genk'],['圣吉罗斯联合','USG','比甲',77,'#d8bd25','attack','Union Saint-Gilloise'],
 ['佩纳罗尔','PEN','乌甲',75,'#d6b927','physical','Penarol'],['乌拉圭民族','NAC','乌甲',75,'#2762a8','youth','Club Nacional de Football'],['防卫者体育','DEF','乌甲',70,'#733b91','youth','Defensor Sporting'],
 ['法马利康','FAM','葡超',72,'#203d79','youth','FC Famalicao'],['阿罗卡','ARO','葡超',69,'#d5b82b','physical','FC Arouca'],['卡萨皮亚','CAS','葡超',68,'#222222','physical','Casa Pia AC'],['埃斯托里尔','EST','葡超',69,'#e2c526','youth','Estoril Praia'],['里奥阿维','RIO','葡超',68,'#258b58','physical','Rio Ave FC'],['莫雷拉人','MOR','葡超',69,'#267f52','physical','Moreirense FC'],['吉尔维森特','GIL','葡超',69,'#c72735','attack','Gil Vicente FC'],['圣克拉拉','SCL','葡超',70,'#c92b39','physical','CD Santa Clara'],
 ['乌德勒支','UTR','荷甲',76,'#c92a38','attack','FC Utrecht'],['奈梅亨','NEC','荷甲',73,'#c62a39','youth','NEC Nijmegen'],['前进之鹰','GAE','荷甲',72,'#c92b37','physical','Go Ahead Eagles'],['海伦芬','HEE','荷甲',71,'#2b72b7','youth','SC Heerenveen'],['鹿特丹斯巴达','SPA','荷甲',70,'#c72b39','physical','Sparta Rotterdam'],['格罗宁根','GRO','荷甲',69,'#258255','youth','FC Groningen'],['兹沃勒','PEC','荷甲',68,'#2769ad','physical','PEC Zwolle'],['福图纳锡塔德','FOR','荷甲',67,'#d7bd29','physical','Fortuna Sittard'],['布雷达','NAC','荷甲',67,'#d6b92b','physical','NAC Breda'],
 ['萨斯菲尔德','VEL','阿甲',74,'#2764a7','youth','Velez Sarsfield'],['贝尔格拉诺','BEL','阿甲',69,'#68a8dc','physical','Belgrano de Cordoba'],['班菲尔德','BAN','阿甲',68,'#26824e','youth','Banfield'],['萨米恩托','SAR','阿甲',66,'#278252','physical','Sarmiento de Junin'],['阿尔多西维','ALD','阿甲',65,'#d8bd2a','physical','Aldosivi'],['戈多伊克鲁斯','GOD','阿甲',70,'#275aa1','attack','Godoy Cruz'],['蒂格雷','TIG','阿甲',69,'#2855a0','youth','Tigre'],
 ['福塔雷萨','FOR','巴甲',74,'#2456a0','physical','Fortaleza EC'],['布拉甘蒂诺红牛','RBB','巴甲',74,'#c62b39','youth','Red Bull Bragantino'],['塞阿拉','CEA','巴甲',69,'#222222','physical','Ceara SC'],['累西腓体育','SPO','巴甲',68,'#c52937','physical','Sport Recife'],['尤文图德','JUV','巴甲',67,'#288352','physical','EC Juventude'],['维多利亚','VIT','巴甲',68,'#c72937','physical','EC Vitoria'],['米拉索尔','MIR','巴甲',69,'#d8bd28','youth','Mirassol FC'],
 ['圣何塞地震','SJE','美职联',66,'#21549a','youth','San Jose Earthquakes'],['科罗拉多急流','COL','美职联',66,'#77233b','physical','Colorado Rapids'],['华盛顿联','DCU','美职联',67,'#222222','physical','DC United'],['新英格兰革命','NER','美职联',66,'#214b91','physical','New England Revolution'],['奥斯汀','ATX','美职联',68,'#23844f','attack','Austin FC'],
 ['达马克','DAM','沙特联',67,'#c62938','physical','Damac FC'],['哈萨征服','FAT','沙特联',68,'#2768aa','attack','Al Fateh FC'],['赛哈特海湾','KHA','沙特联',65,'#d8bd27','physical','Al Khaleej Club'],['阿科多','OKH','沙特联',64,'#222222','physical','Al Okhdood Club'],['利雅得体育','RIY','沙特联',64,'#c92b39','youth','Al Riyadh SC'],['达曼协作','ETT','沙特联',71,'#25834e','attack','Al Ettifaq FC'],
 ['邓迪','DUN','苏超',66,'#215ba4','physical','Dundee FC'],['基尔马诺克','KIL','苏超',67,'#2855a0','physical','Kilmarnock FC'],['马瑟韦尔','MOT','苏超',67,'#8b2438','youth','Motherwell FC'],['罗斯郡','ROS','苏超',64,'#1e4c88','physical','Ross County FC'],['圣米伦','STM','苏超',68,'#222222','physical','St Mirren FC'],['利文斯顿','LIV','苏超',64,'#d5b82a','physical','Livingston FC'],
 ['开塞利体育','KAY','土超',69,'#c92b39','physical','Kayserispor'],['科贾埃利体育','KOC','土超',68,'#278250','physical','Kocaelispor'],['加济安泰普','GAZ','土超',68,'#c72b39','physical','Gaziantep FK'],['阿兰亚体育','ALA','土超',69,'#e17c2a','attack','Alanyaspor'],
 ['青岛海牛','QDH','中超',62,'#285da5','physical','Qingdao Hainiu FC'],['长春亚泰','YAT','中超',62,'#c52b38','youth','Changchun Yatai FC'],['武汉三镇','WTT','中超',65,'#2855a0','attack','Wuhan Three Towns FC'],['深圳新鹏城','SZP','中超',62,'#285fa5','youth','Shenzhen Peng City FC'],['青岛西海岸','QDW','中超',63,'#d6b828','physical','Qingdao West Coast FC'],['河南','HEN','中超',64,'#c62b39','physical','Henan FC'],
 ['奥伦堡','ORE','俄超',65,'#2873b6','physical','FC Orenburg'],['马哈奇卡拉迪纳摩','DMK','俄超',64,'#285fa5','physical','Dynamo Makhachkala'],['下诺夫哥罗德','PNN','俄超',64,'#2858a2','physical','Pari Nizhny Novgorod'],['陶里亚蒂阿克隆','AKR','俄超',66,'#c82b39','youth','Akron Tolyatti'],['加里宁格勒波罗的海','BAL','俄超',66,'#285da4','physical','Baltika Kaliningrad'],
 ['登德尔','DEN','比甲',64,'#275ba2','physical','FCV Dender EH'],['色格拉布鲁日','CER','比甲',68,'#25824f','youth','Cercle Brugge KSV'],['奥德赫维里','OHL','比甲',67,'#c62b39','youth','Oud-Heverlee Leuven'],['聚尔特瓦勒海姆','ZUL','比甲',65,'#c52b39','physical','SV Zulte Waregem'],['拉卢维耶尔','LAL','比甲',63,'#278252','physical','RAAL La Louviere'],
 ['米拉马尔米西奥内斯','MIR','乌甲',64,'#c82b39','youth','Miramar Misiones'],['塞罗','CER','乌甲',64,'#2759a2','physical','CA Cerro'],['普罗格雷索','PRO','乌甲',63,'#d7bd28','physical','CA Progreso'],['蒙得维的亚流浪者','WAN','乌甲',65,'#222222','youth','Montevideo Wanderers']
].map(x=>C(...x));

const PLANS=[
 {id:'tech',name:'技术',attr:'tech',bonus:1.45},
 {id:'body',name:'身体',attr:'physical',bonus:1.35},
 {id:'mind',name:'球商',attr:'mind',bonus:1.4}
];
const STRATEGIES=[
 {id:'minutes',name:'出场'},
 {id:'numbers',name:'数据'},
 {id:'trophies',name:'荣誉'}
];
const ICONS={
 tech:'<svg viewBox="0 0 32 32"><circle cx="16" cy="16" r="11"/><path d="m16 10 4 3-1.5 5h-5L12 13l4-3Zm-4 3-5 1m13-1 5 1m-6.5 4 3 5m-8-5-3 5"/></svg>',
 body:'<svg viewBox="0 0 32 32"><path d="M7 13v6m4-9v12m10-12v12m4-9v6M7 16h18M4 12h3v8H4zm21 0h3v8h-3z"/></svg>',
 mind:'<svg viewBox="0 0 32 32"><circle cx="16" cy="8" r="3"/><circle cx="8" cy="22" r="3"/><circle cx="24" cy="22" r="3"/><path d="m14.5 10.5-5 8.5m8-8.5 5 8.5M11 22h10"/></svg>',
 minutes:'<svg viewBox="0 0 32 32"><circle cx="16" cy="17" r="11"/><path d="M16 11v7l5 3M12 4h8"/></svg>',
 numbers:'<svg viewBox="0 0 32 32"><path d="M6 26V15h5v11m5 0V9h5v17m5 0V5h-5"/><path d="M4 26h24"/></svg>',
 trophies:'<svg viewBox="0 0 32 32"><path d="M10 5h12v7c0 5-2.5 8-6 8s-6-3-6-8V5Zm2 20h8m-4-5v5M10 8H6v3c0 3 2 5 5 5m11-8h4v3c0 3-2 5-5 5"/></svg>'
};
const CUP_BY_LEAGUE={英超:'足总杯',西甲:'国王杯',意甲:'意大利杯',德甲:'德国杯',法甲:'法国杯',葡超:'葡萄牙杯',荷甲:'荷兰杯',阿甲:'阿根廷杯',巴甲:'巴西杯',美职联:'美国公开杯',沙特联:'沙王冠',苏超:'苏格兰杯',土超:'土耳其杯',中超:'足协杯',俄超:'俄罗斯杯',比甲:'比利时杯',乌甲:'乌拉圭杯'};
const LEAGUE_SYSTEMS={英超:'英冠',西甲:'西乙',意甲:'意乙',德甲:'德乙',法甲:'法乙'};
const TOP_BY_SECOND=Object.fromEntries(Object.entries(LEAGUE_SYSTEMS).map(([top,second])=>[second,top]));
const CONTINENTAL_BY_LEAGUE={英超:'欧冠',西甲:'欧冠',意甲:'欧冠',德甲:'欧冠',法甲:'欧冠',葡超:'欧冠',荷甲:'欧冠',苏超:'欧冠',土超:'欧冠',俄超:'欧冠',比甲:'欧冠',阿甲:'解放者杯',巴甲:'解放者杯',乌甲:'解放者杯',中超:'亚冠',沙特联:'亚冠',美职联:'中北美冠军杯'};
const TITLE_BASE={
 曼城:31,利物浦:24,阿森纳:20,切尔西:8,曼联:6,纽卡斯尔联:4,热刺:7,阿斯顿维拉:2,
 皇家马德里:40,巴塞罗那:38,马德里竞技:8,毕尔巴鄂竞技:2,比利亚雷亚尔:1,皇家贝蒂斯:.7,皇家社会:.7,
 国际米兰:30,那不勒斯:22,尤文图斯:20,AC米兰:14,亚特兰大:8,罗马:3,拉齐奥:1.5,佛罗伦萨:1,博洛尼亚:1,
 拜仁:56,勒沃库森:22,多特蒙德:12,莱比锡:7,法兰克福:1.5,斯图加特:1,
 巴黎圣日耳曼:65,摩纳哥:10,马赛:8,里尔:5,里昂:3,雷恩:1,尼斯:1
};
const BIG_FIVE=new Set(Object.keys(LEAGUE_SYSTEMS));
const LEAGUE_STRENGTH_ADJUST={英超:1,西甲:0,意甲:0,德甲:0,法甲:-1,葡超:-2,荷甲:-2,苏超:-5,土超:-4,俄超:-6,比甲:-4,阿甲:-6,巴甲:-5,乌甲:-8,中超:-10,沙特联:-6,美职联:-7};
const NATIONS={
 中国:{strength:63,confed:'AS'},阿根廷:{strength:91,confed:'SA'},巴西:{strength:91,confed:'SA'},乌拉圭:{strength:84,confed:'SA'},法国:{strength:92,confed:'EU'},德国:{strength:88,confed:'EU'},英格兰:{strength:90,confed:'EU'},苏格兰:{strength:78,confed:'EU'},西班牙:{strength:91,confed:'EU'},葡萄牙:{strength:89,confed:'EU'},意大利:{strength:86,confed:'EU'},比利时:{strength:85,confed:'EU'},荷兰:{strength:87,confed:'EU'},土耳其:{strength:79,confed:'EU'},俄罗斯:{strength:78,confed:'EU'},沙特阿拉伯:{strength:72,confed:'AS'},美国:{strength:80,confed:'NA'},克罗地亚:{strength:83,confed:'EU'},挪威:{strength:81,confed:'EU'},日本:{strength:80,confed:'AS'},韩国:{strength:79,confed:'AS'},墨西哥:{strength:80,confed:'NA'},摩洛哥:{strength:82,confed:'AF'},瑞士:{strength:81,confed:'EU'},哥伦比亚:{strength:84,confed:'SA'},丹麦:{strength:80,confed:'EU'},塞内加尔:{strength:81,confed:'AF'},尼日利亚:{strength:79,confed:'AF'}
};
const HOME_LEAGUE={中国:'中超',阿根廷:'阿甲',巴西:'巴甲',乌拉圭:'乌甲',法国:'法甲',德国:'德甲',英格兰:'英超',苏格兰:'苏超',西班牙:'西甲',葡萄牙:'葡超',意大利:'意甲',比利时:'比甲',荷兰:'荷甲',土耳其:'土超',俄罗斯:'俄超',沙特阿拉伯:'沙特联',美国:'美职联'};
const COMPETITION_MAX={世界杯:8,欧洲杯:7,美洲杯:7,亚洲杯:7,非洲杯:7,欧国联:8,欧美杯:1};
const CONTENT=window.CAREER_CONTENT_DATA||{};
const LEAGUE_AWARDS=CONTENT.leagueAwards||{};
const SUPER_CUPS=CONTENT.superCups||{};
const MILESTONE_THRESHOLDS=CONTENT.milestoneThresholds||{apps:[50,100,200,300,500],goals:[50,100,200,300],assists:[50,100,200],cleanSheets:[50,100,150]};
const NATIONAL_KITS=CONTENT.nationalKits||{};
const POS_STATS={
 ST:{goal:.55,assist:.16,keys:['shoot','pace','composure'],group:'attack',number:9,boost:{shoot:7,pace:2,composure:3}},
 CF:{goal:.43,assist:.25,keys:['shoot','tech','vision'],group:'attack',number:10,boost:{shoot:5,tech:4,vision:3}},
 LW:{goal:.34,assist:.28,keys:['pace','tech','shoot'],group:'wing',number:11,boost:{pace:5,tech:4,shoot:2}},
 RW:{goal:.34,assist:.28,keys:['pace','tech','vision'],group:'wing',number:7,boost:{pace:5,tech:4,vision:2}},
 CAM:{goal:.23,assist:.38,keys:['vision','tech','shoot'],group:'midfield',number:10,boost:{vision:6,tech:4,shoot:2}},
 LM:{goal:.17,assist:.31,keys:['pace','vision','tech'],group:'midfield',number:11,boost:{pace:4,vision:4,tech:2}},
 CM:{goal:.14,assist:.32,keys:['vision','tech','composure'],group:'midfield',number:8,boost:{vision:6,tech:3,composure:2}},
 RM:{goal:.17,assist:.31,keys:['pace','vision','tech'],group:'midfield',number:7,boost:{pace:4,vision:4,tech:2}},
 CDM:{goal:.07,assist:.19,keys:['defense','vision','physical'],group:'defense',number:6,boost:{defense:8,vision:4,physical:4,shoot:-3}},
 LWB:{goal:.08,assist:.23,keys:['pace','defense','physical'],group:'defense',number:3,boost:{pace:5,defense:7,physical:3,shoot:-3}},
 LB:{goal:.04,assist:.15,keys:['defense','pace','physical'],group:'defense',number:3,boost:{defense:10,pace:4,physical:3,shoot:-5}},
 CB:{goal:.05,assist:.05,keys:['defense','physical','composure'],group:'defense',number:4,boost:{defense:12,physical:6,composure:3,shoot:-6}},
 RB:{goal:.04,assist:.15,keys:['defense','pace','physical'],group:'defense',number:2,boost:{defense:10,pace:4,physical:3,shoot:-5}},
 RWB:{goal:.08,assist:.23,keys:['pace','defense','physical'],group:'defense',number:2,boost:{pace:5,defense:7,physical:3,shoot:-3}},
 GK:{goal:.001,assist:.01,keys:['defense','composure','physical'],group:'keeper',number:1,boost:{defense:15,composure:7,physical:4,pace:-8,shoot:-12}}
};
const LEGACY_POSITIONS={边锋:'LW',中场:'CM',前锋:'ST',后卫:'CB'};

let game=null,chosenPlan=null,chosenStrategy=null,chosenOffer=null,offerList=[];
const rand=(min,max)=>Math.random()*(max-min)+min;
const rint=(min,max)=>Math.round(rand(min,max));
const pick=a=>a[Math.floor(Math.random()*a.length)];

function initialAttrs(position,age=16){
 const r=Math.random();const level=(r<.55?rint(50,55):r<.9?rint(56,60):r<.985?rint(61,65):rint(66,69))+(age-16)*1.25;const a={tech:level+rint(-1,2),pace:level+rint(-1,3),shoot:level+rint(-3,1),vision:level+rint(-2,2),physical:level+rint(-3,1),defense:level+rint(-8,-2),composure:level+rint(-3,1)};
 Object.entries(POS_STATS[position].boost).forEach(([key,value])=>a[key]+=value);
 return a;
}
function calcOverall(attrs,position){return Math.round(POS_STATS[position].keys.reduce((n,k)=>n+attrs[k],0)/3)}
function rollPotential(overall){const r=Math.random();const rolled=r<.2?rint(70,78):r<.7?rint(79,87):r<.95?rint(88,92):rint(93,95);return Math.max(overall+2,rolled)}
function composePlayerName(family,given,nationality){family=family.trim();given=given.trim();if(!family&&!given)return'小将';if(!family||!given)return family||given;return['中国','日本','韩国'].includes(nationality)?`${family}${given}`:`${given} ${family}`}
function rollInitialValue(age,overall,potential){const ageFactor=1+(age-16)*.32;const abilityFactor=Math.max(.45,(overall-57)/9);const potentialFactor=1+Math.max(0,potential-82)*.035;const r=Math.random();const market=r<.58?rand(.12,.55):r<.9?rand(.55,1.35):r<.985?rand(1.35,3.2):rand(3.2,6);return Math.round(clamp(market*ageFactor*abilityFactor*potentialFactor,.08,8)*10)/10}
function rollHiddenTraits(){const traits={};const physique=Math.random();if(physique<.07)traits.ironman=true;else if(physique<.15)traits.fragile=true;if(Math.random()<.08)traits.professional=true;if(Math.random()<.06)traits.bigGame=true;if(Math.random()<.07)traits.lateBloomer=true;return traits}
function newGame(name,position,nationality,age,number){const attrs=initialAttrs(position,age);const overall=calcOverall(attrs,position);const potential=rollPotential(overall);return{name,position,nationality,needsNationality:false,number:Math.round(clamp(number||POS_STATS[position].number,1,99)),age,year:2026,season:1,potential,hiddenTraits:rollHiddenTraits(),attrs,overall,club:null,value:rollInitialValue(age,overall,potential),reputation:8,totalApps:0,totalGoals:0,totalAssists:0,totalCleanSheets:0,totalSaves:0,totalNationalApps:0,totalNationalGoals:0,trophyCount:0,honors:[],history:[],milestoneFlags:{},awardFlags:{},clubRecordFees:{},clubDynamics:{},clubNews:[],retired:false,finalissimaYear:null}}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(game));$('#save-label').textContent='已存档'}
function load(){try{const saved=JSON.parse(localStorage.getItem(SAVE_KEY));if(!saved)return null;if(LEGACY_POSITIONS[saved.position])saved.position=LEGACY_POSITIONS[saved.position];if(!POS_STATS[saved.position])saved.position='ST';if(!saved.number)saved.number=POS_STATS[saved.position].number;if(!saved.nationality){saved.nationality='中国';saved.needsNationality=true}saved.hiddenTraits=saved.hiddenTraits||{};saved.totalNationalApps=saved.totalNationalApps||0;saved.totalNationalGoals=saved.totalNationalGoals||0;saved.totalCleanSheets=saved.totalCleanSheets||0;saved.totalSaves=saved.totalSaves||0;saved.milestoneFlags=saved.milestoneFlags||{};saved.awardFlags=saved.awardFlags||{};saved.clubRecordFees=saved.clubRecordFees||{};saved.clubDynamics=saved.clubDynamics||{};saved.clubNews=saved.clubNews||[];(saved.history||[]).forEach(r=>{r.teamHonors=(r.teamHonors||[]).map(h=>h==='国内杯冠军'?(CUP_BY_LEAGUE[r.club?.league]||'杯赛冠军'):h);r.personal=r.personal||[];r.nationalHonors=r.nationalHonors||[];r.seasonStages=r.seasonStages||[];r.milestones=r.milestones||[];const max=COMPETITION_MAX[r.national?.competition];if(max&&r.national.apps>max){saved.totalNationalApps=Math.max(0,saved.totalNationalApps-(r.national.apps-max));r.national.apps=max}});let removedSuperCups=0;(saved.history||[]).forEach((r,i)=>{r.teamHonors=r.teamHonors.filter(h=>{if(!isSuperCupHonor(h))return true;const valid=h===SUPER_CUPS[r.club?.league]&&superCupEligibilityFromPrevious(r.club,saved.history[i+1]);if(!valid)removedSuperCups++;return valid})});saved.trophyCount=Math.max(0,(saved.trophyCount||0)-removedSuperCups);return saved}catch{return null}}
function formatMoney(v){return v>=100?`€${Math.round(v)}M`:v>=10?`€${v.toFixed(0)}M`:`€${v.toFixed(1)}M`}
function yearLabel(){return `${game.year} / ${String(game.year+1).slice(-2)}`}

function renderGame(){
 $('#setup').hidden=true;$('#game').hidden=false;$('#player-card-name').textContent=game.name;$('#player-position').textContent=game.position;$('#shirt-no').textContent=game.number;$('#current-club').textContent=game.club?.name||'等待第一份职业合同';$('#player-nationality').textContent=game.nationality;
 const kit=NATIONAL_KITS[game.nationality]||{primary:'#dbe3ff',secondary:'#ffffff',accent:'#2439a8',pattern:'solid'};const shirt=$('.shirt');shirt.dataset.kit=kit.pattern;shirt.style.setProperty('--kit1',kit.primary);shirt.style.setProperty('--kit2',kit.secondary);shirt.style.setProperty('--kit3',kit.accent);
 $('#nationality-migration').hidden=!game.needsNationality;if(game.needsNationality)$('#passport-nationality').innerHTML=Object.keys(NATIONS).map(n=>`<option${n===game.nationality?' selected':''}>${n}</option>`).join('');
 $('#overall').textContent=game.overall;$('#age').textContent=game.age;$('#value').textContent=formatMoney(game.value);$('#apps').textContent=game.totalApps;$('#trophies').textContent=game.trophyCount;$('#national-apps').textContent=game.totalNationalApps;$('#national-goals').textContent=game.totalNationalGoals;
 $('#season-title').textContent=`${yearLabel()} 赛季`;$('#season-count').textContent=`第 ${game.season} 季`;$('#progress').style.setProperty('--p',`${Math.min(100,game.season/18*100)}%`);
 const labels={tech:'技术',pace:'速度',shoot:'射门',vision:'视野',physical:'身体',defense:'防守',composure:'沉着'};
 $('#attributes').innerHTML=Object.entries(game.attrs).map(([k,v])=>`<div class="attribute"><span>${labels[k]}</span><i style="--v:${v}%"></i><b>${v}</b></div>`).join('');
 renderHonorCabinet();renderTimeline();renderChoices();save();
}

function renderChoices(){
 chosenPlan=chosenStrategy=chosenOffer=null;
 $('#plans').innerHTML=PLANS.map(x=>`<button class="plan" data-plan="${x.id}"><span class="choice-icon" aria-hidden="true">${ICONS[x.id]}</span><b>${x.name}</b></button>`).join('');
 $('#strategies').innerHTML=STRATEGIES.map(x=>`<button class="plan" data-strategy="${x.id}"><span class="choice-icon" aria-hidden="true">${ICONS[x.id]}</span><b>${x.name}</b></button>`).join('');
 document.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>selectOne('plan',b.dataset.plan,b));document.querySelectorAll('[data-strategy]').forEach(b=>b.onclick=()=>selectOne('strategy',b.dataset.strategy,b));
 offerList=generateOffers();$('#offers').innerHTML=offerList.map((o,i)=>offerHTML(o,i)).join('');document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>selectOffer(+b.dataset.offer,b));hydrateOfferBadges();updateReady();
}
function selectOne(type,id,button){const selector=type==='plan'?'[data-plan]':'[data-strategy]';document.querySelectorAll(selector).forEach(x=>x.classList.toggle('selected',x===button));if(type==='plan')chosenPlan=PLANS.find(x=>x.id===id);else chosenStrategy=STRATEGIES.find(x=>x.id===id);updateReady()}
function selectOffer(i,button){chosenOffer=offerList[i];document.querySelectorAll('[data-offer]').forEach(x=>x.classList.toggle('selected',x===button));updateReady()}
function updateReady(){const ready=chosenPlan&&chosenStrategy&&chosenOffer;$('#simulate').disabled=!ready;$('#decision-note').textContent=!chosenPlan?'先定发展方向。':!chosenStrategy?'再选这一年怎么踢。':!chosenOffer?'最后签一份合同。':`${chosenOffer.moveType} · ${chosenOffer.club.name} · ${chosenOffer.role} · ${chosenPlan.name}。`}

function clubPower(club){const source=CLUBS.find(c=>c.name===club.name);const base=source?.power??club.power;const league=source?.league||club.league;return Math.round(clamp(base+(LEAGUE_STRENGTH_ADJUST[league]||0)+(game.clubDynamics?.[club.name]||0),53,96))}
function evolveClubPowers(){
 const shocks=[{label:'青训一代集中涌现',shift:4},{label:'新投资者增资',shift:5},{label:'名帅与管理层改革',shift:3},{label:'核心阵容老化',shift:-3},{label:'主力大规模流失',shift:-4},{label:'财政危机',shift:-6}];const news=[];game.clubDynamics=game.clubDynamics||{};
 CLUBS.forEach(club=>{let delta=(game.clubDynamics[club.name]||0)*.82+rand(-1.15,1.15);if(Math.random()<.055){const shock=pick(shocks);delta+=shock.shift;news.push({club:club.name,label:shock.label,change:shock.shift})}game.clubDynamics[club.name]=Math.round(clamp(delta,-9,9)*10)/10});
 game.clubNews=news.sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,8);if(game.club)game.club.power=clubPower(game.club)
}
function applyClubSeasonImpact(club,honors,movement){let shift=0,label='';if(movement?.type==='relegated'){shift=-3;label='降级导致阵容流失'}else if(movement?.type==='promoted'){shift=2;label='升级带来资源增长'}else if(honors.some(h=>h===`${club.league}冠军`)){shift=1.5;label='联赛夺冠提升吸引力'}if(!shift)return'';game.clubDynamics[club.name]=clamp((game.clubDynamics[club.name]||0)+shift,-9,9);return`${label} · 球队实力 ${shift>0?'+':''}${shift}`}

function generateOffers(){
 const current=game.club;const decision=clubWindowDecision(current);const total=rint(3,5);const slots=current?total-1:total;const recent=new Set(game.lastOffers||[]);
 const firstLeague=decision.mode==='first'?(HOME_LEAGUE[game.nationality]||pick([...new Set(CLUBS.map(c=>c.league))])):null;
 const low=Math.max(63,game.overall-(decision.mode==='stay'?14:18));const high=Math.min(96,game.overall+(decision.mode==='stay'?10:6)+game.reputation*.05);let pool=firstLeague?CLUBS.filter(c=>c.league===firstLeague):CLUBS.filter(c=>c.name!==current?.name&&clubPower(c)>=low&&clubPower(c)<=high);
 if(!firstLeague&&pool.length<slots*3)pool=CLUBS.filter(c=>c.name!==current?.name&&clubPower(c)<=high+6&&clubPower(c)>=low-6);
 pool=pool.map(c=>({club:c,score:Math.random()*72-Math.abs(clubPower(c)-(game.overall+(decision.mode==='stay'?1:-2)))*1.05-(recent.has(c.name)?15:0)+(c.league!==current?.league?rand(0,9):0)})).sort((a,b)=>b.score-a.score).map(x=>x.club).slice(0,slots);
 const offers=[];if(current)offers.push(makeOffer(current,'留队',true));const moveType=decision.mode==='first'?'首份合同':decision.mode==='loan'?'租借':decision.mode==='release'?'自由签约':'转会';offers.push(...pool.map(club=>makeOffer(club,moveType,false)));game.lastOffers=offers.map(o=>o.club.name);return offers
}
function clubWindowDecision(current){
 if(!current)return{mode:'first',message:'等待第一份职业合同'};const gap=current.power-game.overall;const lastRating=parseFloat(game.history[0]?.rating||'7');let exitRisk=0;if(gap>=8)exitRisk+=.5;else if(gap>=5)exitRisk+=.25;if(lastRating<6.5)exitRisk+=.28;else if(lastRating<6.8)exitRisk+=.12;if(game.age>=32)exitRisk+=(game.age-31)*.09;if(game.age>=35)exitRisk+=.22;
 if(Math.random()>=Math.min(.94,exitRisk))return{mode:'stay',message:'俱乐部愿意提供留队合同'};if(game.age<=29&&gap>=4&&Math.random()<.62)return{mode:'loan',message:'俱乐部建议外租，但你仍可选择留队竞争'};if(game.age>=34)return{mode:'release',message:'续约谈判开放，也可以自由选择新球队'};return{mode:'sale',message:'收到转会报价，你仍然可以拒绝并留队'}
}
function makeOffer(sourceClub,moveType,stay){const club={...sourceClub,power:clubPower(sourceClub)};const gap=game.overall-club.power;let role=gap>=3?'绝对核心':gap>=-2?'主力':gap>=-7?'轮换':'替补';const firstContract=moveType==='首份合同';if(firstContract&&game.age<=16)role=gap>=-5?'轮换':'替补';else if(firstContract&&game.age<=18&&role==='绝对核心')role='主力';else if(game.age<=19&&game.reputation<25&&role==='绝对核心')role='主力';const wage=Math.max(8,Math.round((club.power-62)*7+(game.overall-60)*5+rand(-15,25)));const paidTransfer=!stay&&moveType==='转会';const fee=paidTransfer?Math.max(1,Math.round(game.value*rand(.82,1.28))):0;const news=(game.clubNews||[]).find(n=>n.club===club.name);const promise=firstContract?(role==='主力'?'进入一线队轮换':'重点培养与杯赛机会'):role==='绝对核心'?'围绕你建队':role==='主力'?'稳定首发':role==='轮换'?'竞争主力':'杯赛机会';return{club,role,wage,fee,stay,moveType,news,fit:fitScore(club),promise}}
function fitScore(club){const group=POS_STATS[game.position].group;const good=(club.style==='youth'&&game.age<=22)||(club.style==='attack'&&!['defense','keeper'].includes(group))||(club.style==='physical'&&['defense','attack','keeper'].includes(group))||(club.style==='star'&&game.reputation>38);return good?1.08:.96}
function offerHTML(o,i){return `<button class="offer" data-offer="${i}"><div class="offer-top"><span class="crest" data-crest="${i}" style="--club:${o.club.color}"><span>${o.club.abbr}</span></span><div><b>${o.club.name}<em class="move-type">${o.moveType}</em></b><small>${o.club.league} · ${o.promise}${o.news?` · ${o.news.label} ${o.news.change>0?'+':''}${o.news.change}`:''}</small></div></div><div class="offer-meta"><span>球队实力<b>${o.club.power}</b></span><span>承诺角色<b>${o.role}</b></span><span>周薪<b>€${o.wage}K</b></span><span>转会费<b>${o.fee?formatMoney(o.fee):'—'}</b></span></div></button>`}
async function hydrateOfferBadges(){
 const slots=[...document.querySelectorAll('[data-crest]')];slots.forEach(slot=>{const club=offerList[+slot.dataset.crest]?.club;if(!club)return;const img=new Image();img.alt=`${club.name}队徽`;img.width=48;img.height=48;img.decoding='async';img.onload=()=>slot.replaceChildren(img);img.src=club.crest})
}

function simulateSeason(){
 const offer=chosenOffer,club=offer.club,previousClub=game.club,roleBase={绝对核心:42,主力:36,轮换:25,替补:14}[offer.role];const previous={apps:game.totalApps,goals:game.totalGoals,assists:game.totalAssists,cleanSheets:game.totalCleanSheets||0,nationalApps:game.totalNationalApps,trophies:game.trophyCount,personal:game.honors.length};let apps=roleBase+rint(-3,3);const injury=rollInjury();let growth=rollGrowth();const beforeOverall=game.overall;
 if(chosenStrategy.id==='minutes'){apps+=4;growth+=.5}if(chosenStrategy.id==='numbers')growth+=.4;if(chosenStrategy.id==='trophies'){apps-=2;growth+=offer.fit>.99?.5:0}if(injury){apps-=injury.missed;growth-=injury.growthPenalty}
 apps=clamp(apps,4,48);const planBoost=chosenPlan.bonus*offer.fit;applyDevelopment(chosenPlan.attr,planBoost,growth);if(injury)applyInjuryImpact(injury);game.overall=calcOverall(game.attrs,game.position);const overallChange=game.overall-beforeOverall;
 const quality=clamp((game.overall+club.power)/2+offer.fit*5+rand(-6,6)+(game.hiddenTraits?.bigGame&&chosenStrategy.id==='trophies'?2:0),45,99);const pos=POS_STATS[game.position];let goals=Math.max(0,Math.round(apps*pos.goal*(quality/80)*rand(.72,1.25)));let assists=Math.max(0,Math.round(apps*pos.assist*(quality/80)*rand(.72,1.25)));
 if(chosenStrategy.id==='numbers'){goals=Math.round(goals*1.22);assists=Math.round(assists*1.17)}if(pos.group==='defense'&&quality>84)assists+=rint(1,4);const isKeeper=pos.group==='keeper';const cleanSheets=isKeeper?clamp(Math.round(apps*clamp(.16+(club.power-70)*.007+(game.overall-66)*.006,.12,.58)*rand(.78,1.18)),0,apps):0;const saves=isKeeper?Math.round(apps*rand(2.25,4.15)):0;
 const rating=isKeeper?clamp(5.75+cleanSheets/Math.max(8,apps)*2.3+saves/Math.max(12,apps)*.19+(quality-75)/55+rand(-.2,.2),5.4,9.2):clamp(5.75+(goals+assists)/Math.max(15,apps)*2.18+(quality-75)/42+rand(-.22,.18),5.3,9.2);const kickerRating=['德甲','德乙'].includes(club.league)?rollKickerRating(rating):null;
 const clubCompetitions=rollTeamHonors(club,quality,chosenStrategy.id==='trophies');const teamHonors=clubCompetitions.honors;const national=rollNationalSeason();const nationalHonors=national.honors;const personal=rollPersonalHonors({goals,assists,apps,cleanSheets,saves,rating,teamHonors,club});
 const valueFactor=Math.max(.5,1-(Math.max(0,game.age-29)*.075));game.value=Math.max(.1,(game.overall-60)**1.78*.15*valueFactor+game.reputation*.32);
 game.reputation=clamp(game.reputation+(rating-6.2)*5+teamHonors.length*3+personal.length*7+nationalHonors.length*5,0,100);game.totalApps+=apps;game.totalGoals+=goals;game.totalAssists+=assists;game.trophyCount+=teamHonors.length+nationalHonors.length;game.honors.push(...personal);if(offer.moveType==='租借'&&previousClub)game.parentClub={...previousClub};else if(offer.moveType!=='留队')game.parentClub=null;game.club={...club};
 game.totalCleanSheets=(game.totalCleanSheets||0)+cleanSheets;game.totalSaves=(game.totalSaves||0)+saves;const seasonClub={...game.club};const leagueMovement=rollLeagueMovement(game.club,quality,teamHonors);const clubEvent=applyClubSeasonImpact(seasonClub,teamHonors,leagueMovement);if(leagueMovement)game.club.league=leagueMovement.to;const milestones=collectMilestones(previous,{apps,goals,assists,cleanSheets,personal,teamHonors,nationalHonors,national,offer});const seasonStages=[...clubCompetitions.stages,...(national.stage?[`${national.competition} · ${national.stage}`]:[])];
 const record={season:yearLabel(),age:game.age,club:seasonClub,clubPower:club.power,moveType:offer.moveType,transferFee:offer.fee,role:offer.role,overall:game.overall,overallChange,apps,goals,assists,cleanSheets,saves,rating:rating.toFixed(1),kickerRating,teamHonors,personal,national,nationalHonors,seasonStages,milestones,leagueMovement,clubEvent,injury:injury?.label||'',injurySeverity:injury?.severity||'',plan:chosenPlan.name,strategy:chosenStrategy.name};game.history.unshift(record);showReport(record);save();
}
function rollKickerRating(rating){const strict=clamp(4.05-(rating-6.35)*.92+rand(-.2,.22),1.15,5.65);return(Math.round(strict*20)/20).toFixed(2)}
function collectMilestones(previous,s){const out=[];game.milestoneFlags=game.milestoneFlags||{};const add=(id,label)=>{if(!game.milestoneFlags[id]){game.milestoneFlags[id]=true;out.push(label)}};if(previous.apps===0&&s.apps)add('debut','职业生涯首秀');if(previous.goals===0&&s.goals)add('firstGoal','职业生涯首球');if(previous.assists===0&&s.assists)add('firstAssist','职业生涯首次助攻');if(s.goals>=3&&Math.random()<Math.min(.62,s.goals/Math.max(1,s.apps)*.42))add('hatTrick','职业生涯首次帽子戏法');[['apps','出场'],['goals','进球'],['assists','助攻'],['cleanSheets','零封']].forEach(([key,label])=>(MILESTONE_THRESHOLDS[key]||[]).forEach(n=>{if(previous[key]<n&&game[`total${key[0].toUpperCase()+key.slice(1)}`]>=n)add(`${key}${n}`,`${label}达到 ${n}`)}));if(previous.nationalApps===0&&s.national.called)add('nationalDebut','国家队首秀');if(previous.trophies===0&&(s.teamHonors.length+s.nationalHonors.length))add('firstTrophy','首座冠军奖杯');if(previous.personal===0&&s.personal.length)add('firstIndividualAward','首项个人奖项');if(s.offer.fee){const old=game.clubRecordFees[s.offer.club.name]||0;const threshold=s.offer.club.power>=89?80:s.offer.club.power>=84?48:s.offer.club.power>=78?28:14;if(s.offer.fee>old&&s.offer.fee>=threshold)add(`recordFee-${s.offer.club.name}`,`刷新${s.offer.club.name}队史转会费纪录 · ${formatMoney(s.offer.fee)}`);game.clubRecordFees[s.offer.club.name]=Math.max(old,s.offer.fee)}return out}
function applyDevelopment(focus,bonus,growth){
 const keyAttrs=new Set(POS_STATS[game.position].keys);Object.keys(game.attrs).forEach(k=>{let add=keyAttrs.has(k)?growth+rand(-.8,.8):growth*.28+rand(-.35,.35);if(focus==='tech'&&['tech','shoot'].includes(k))add+=bonus*.45;if(focus==='physical'&&['pace','physical'].includes(k))add+=bonus*.45;if(focus==='mind'&&['vision','composure','defense'].includes(k))add+=bonus*.4;game.attrs[k]=Math.round(clamp(game.attrs[k]+add,35,game.potential))})
}
function rollGrowth(){
 const r=Math.random();let growth;if(game.age<=20)growth=r<.16?0:r<.46?rint(1,2):r<.78?rint(3,4):r<.94?rint(5,6):rint(7,9);else if(game.age<=24)growth=r<.24?0:r<.61?rint(1,2):r<.87?rint(3,4):r<.97?rint(5,6):rint(7,8);else if(game.age<=28)growth=r<.36?0:r<.79?rint(1,2):r<.95?rint(3,4):rint(5,6);else if(game.age<=31)growth=r<.25?-1:r<.72?0:r<.94?1:2;else if(game.age<=34)growth=r<.46?-1:r<.72?-2:r<.94?0:1;else growth=r<.5?-2:r<.82?-1:r<.95?-3:0;if(game.hiddenTraits?.professional)growth+=.45;if(game.hiddenTraits?.lateBloomer)growth+=game.age>=24&&game.age<=29?.75:game.age<=21?-.2:0;return growth
}
function injuryRisk(){game.injuryHistory=game.injuryHistory||{};const prior=Object.values(game.injuryHistory).reduce((sum,n)=>sum+n,0);let risk=.22+(chosenPlan.id==='body'?.035:0)+(chosenStrategy.id==='numbers'?.055:0)+(game.age>=30?(game.age-29)*.012:0)+Math.min(.07,prior*.008);if(game.hiddenTraits?.ironman)risk*=.55;if(game.hiddenTraits?.fragile)risk*=1.65;return clamp(risk,.07,.62)}
function rollInjury(){
 game.injuryHistory=game.injuryHistory||{};if(Math.random()>=injuryRisk())return null;
 const injuries=[
  {id:'knock',weight:29,label:'碰撞挫伤',severity:'轻微',missed:[1,2],growth:0},
  {id:'hamstring',weight:22,label:'腿后肌拉伤',severity:'中度',missed:[2,7],growth:1,attrs:{pace:[0,1]},potential:[0,1]},
  {id:'ankle',weight:15,label:'踝关节扭伤',severity:'中度',missed:[2,6],growth:1,attrs:{pace:[0,1],physical:[0,1]}},
  {id:'groin',weight:11,label:'腹股沟内收肌损伤',severity:'中度',missed:[2,6],growth:1,attrs:{physical:[0,1]}},
  {id:'calf',weight:9,label:'小腿肌肉拉伤',severity:'中度',missed:[3,8],growth:1,attrs:{pace:[0,1],physical:[0,1]},potential:[0,1]},
  {id:'mcl',weight:7,label:'膝内侧副韧带损伤',severity:'重度',missed:[4,10],growth:2,attrs:{physical:[0,2]},potential:[0,1]},
  {id:'meniscus',weight:5,label:'半月板损伤',severity:'重度',missed:[6,14],growth:2,attrs:{pace:[0,2],physical:[0,2]},potential:[0,3]},
  {id:'fracture',weight:.8,label:'足部或腿部骨折',severity:'重度',missed:[10,20],growth:3,attrs:{pace:[0,2],physical:[1,3]},potential:[1,4]},
  {id:'acl',weight:.7,label:'前十字韧带撕裂',severity:'严重',missed:[25,36],growth:4,attrs:{pace:[1,4],physical:[1,3]},potential:[2,6]},
  {id:'achilles',weight:.5,label:'跟腱断裂',severity:'严重',missed:[18,28],growth:4,attrs:{pace:[2,5],physical:[1,4]},potential:[2,7]}
 ];
 const weighted=injuries.map(x=>({...x,weight:x.weight*(game.injuryHistory[x.id]?1+Math.min(1.2,game.injuryHistory[x.id]*.35):1)*(game.hiddenTraits?.fragile&&x.id!=='knock'?1.2:1)}));let roll=Math.random()*weighted.reduce((sum,x)=>sum+x.weight,0);const injury=weighted.find(x=>(roll-=x.weight)<=0)||weighted[0];game.injuryHistory[injury.id]=(game.injuryHistory[injury.id]||0)+1;let missed=rint(...injury.missed);if(game.hiddenTraits?.ironman)missed=Math.max(1,Math.round(missed*.78));if(game.hiddenTraits?.fragile)missed=Math.round(missed*1.18);return{...injury,missed,growthPenalty:injury.growth,recurrent:game.injuryHistory[injury.id]>1}
}
function applyInjuryImpact(injury){
 const losses=[];Object.entries(injury.attrs||{}).forEach(([attr,range])=>{const loss=rint(...range);if(loss){game.attrs[attr]=Math.max(35,game.attrs[attr]-loss);losses.push(`${{pace:'速度',physical:'身体'}[attr]||attr} -${loss}`)}});const potentialLoss=injury.potential?rint(...injury.potential):0;if(potentialLoss){game.potential=Math.max(game.overall,potentialLoss?game.potential-potentialLoss:game.potential);losses.push(`成长上限受损`)}injury.effect=losses.join('、');injury.label=`${injury.severity} · ${injury.recurrent?'复发性':''}${injury.label} · 缺阵约 ${injury.missed} 场${injury.effect?` · ${injury.effect}`:''}`
}
function rollTeamHonors(club,quality,trophyPush){
 const honors=[],stages=[];const boost=trophyPush?4:0;const leagueChance=leagueTitleChance(club,quality,trophyPush);if(Math.random()*100<leagueChance)honors.push(`${club.league}冠军`);else if(leagueChance>=3&&Math.random()*100<clamp(leagueChance*1.35,2,34))stages.push(`${club.league} · 亚军`);
 const cup=CUP_BY_LEAGUE[club.league];if(cup){const cupChance=clamp(2+Math.max(0,club.power-72)*.85+(quality-78)*.18+boost*.65,1,27);const result=rollKnockout(cup,cupChance,quality);if(result.honor)honors.push(result.honor);if(result.stage)stages.push(result.stage)}
 const continental=continentalCompetition(club);if(continental){const tierPenalty=continental==='欧冠'?0:['欧联杯','解放者杯','亚冠精英联赛','中北美冠军杯'].includes(continental)?3:7;const continentalChance=clamp(Math.max(0,club.power-78)*1.12+(quality-80)*.28+boost*.7+tierPenalty,1,24);const result=rollKnockout(continental,continentalChance,quality);if(result.honor)honors.push(result.honor);if(result.stage)stages.push(result.stage)}
 const previousHonors=game.history[0]?.teamHonors||[];if(superCupEligibility(club)){const fourTeam=['西甲','意甲','沙特联'].includes(club.league);if(Math.random()<(fourTeam ? .26 : .48))honors.push(SUPER_CUPS[club.league])}const previousContinental=previousHonors.some(h=>['欧冠冠军','欧联杯冠军','解放者杯冠军','亚冠精英联赛冠军','中北美冠军杯冠军'].includes(h));if(previousContinental&&(game.year+1)%4===1){const result=rollKnockout('世俱杯',clamp(7+(club.power-80)*1.4+(quality-82)*.35,4,35),quality);if(result.honor)honors.push(result.honor);if(result.stage)stages.push(result.stage)}return{honors,stages}
}
function isSuperCupHonor(name){return Object.values(SUPER_CUPS).includes(name)||['苏格兰超级杯冠军','乌拉圭超级杯冠军','美职联冠军杯冠军'].includes(name)}
function superCupEligibility(club){return superCupEligibilityFromPrevious(club,game.history[0])}
function superCupEligibilityFromPrevious(club,previous){const name=SUPER_CUPS[club?.league];if(!previous||!name||previous.club?.name!==club.name)return false;const honors=previous.teamHonors||[],stages=previous.seasonStages||[],leagueTitle=`${club.league}冠军`,cup=CUP_BY_LEAGUE[club.league],cupTitle=cup?`${cup}冠军`:'';if(['西甲','意甲','沙特联'].includes(club.league))return honors.includes(leagueTitle)||honors.includes(cupTitle)||stages.includes(`${club.league} · 亚军`)||stages.includes(`${cup} · 亚军`);return honors.includes(leagueTitle)||honors.includes(cupTitle)}
function continentalCompetition(club){const european=new Set(['英超','西甲','意甲','德甲','法甲','葡超','荷甲','苏超','土超','俄超','比甲']);if(european.has(club.league))return club.power>=82?'欧冠':club.power>=76?'欧联杯':'欧协联';if(['阿甲','巴甲','乌甲'].includes(club.league))return club.power>=73?'解放者杯':'南美杯';if(['中超','沙特联'].includes(club.league))return club.power>=71?'亚冠精英联赛':'亚冠二级联赛';if(club.league==='美职联')return club.power>=72?'中北美冠军杯':'北美联赛杯';return''}
function rollKnockout(name,winChance,quality){if(Math.random()*100<winChance)return{honor:`${name}冠军`,stage:''};const deepChance=clamp(8+winChance*2.25+(quality-78)*1.05,3,76);if(Math.random()*100>=deepChance)return{honor:'',stage:''};const r=Math.random();return{honor:'',stage:`${name} · ${r<.2?'亚军':r<.52?'四强':'八强'}`}}
function leagueTitleChance(club,quality,trophyPush){if(BIG_FIVE.has(club.league)){const base=TITLE_BASE[club.name]??.1;const modifier=clamp(.86+(quality-club.power)*.022+(trophyPush?.12:0),.65,1.3);const carry=game.overall>=91?clamp((game.overall-90)**2*.32,0,12):0;return clamp(base*modifier+carry,.05,68)}return clamp(.25+Math.max(0,club.power-73)**2*.1+(quality-78)*.3+(trophyPush?3:0)+(game.overall>=91?Math.min(10,(game.overall-90)**2*.25):0),.1,52)}
function rollLeagueMovement(club,quality,honors){
 const second=LEAGUE_SYSTEMS[club.league];if(second){const risk=clamp((77-club.power)*4+(72-quality)*2,0,42);if(Math.random()*100<risk)return{type:'relegated',from:club.league,to:second,label:`降入${second}`}}
 const top=TOP_BY_SECOND[club.league];if(top){const champion=honors.includes(`${club.league}冠军`);const chance=champion?100:clamp(24+(club.power-72)*4+(quality-72)*2,12,78);if(Math.random()*100<chance)return{type:'promoted',from:club.league,to:top,label:`升入${top}`}}
 return null
}
function rollPersonalHonors({goals,assists,apps,cleanSheets,rating,teamHonors,club}){
 const h=[],ga=goals+assists,group=POS_STATS[game.position].group;const awards=LEAGUE_AWARDS[club.league]||{scorer:`${club.league}金靴`,creator:`${club.league}助攻王`,keeper:`${club.league}最佳门将`,player:`${club.league}赛季最佳球员`,young:`${club.league}最佳年轻球员`};game.awardFlags=game.awardFlags||{};
 if(!game.awardFlags.goldenBoy&&game.age<=21&&game.overall>=79&&(ga>=17||cleanSheets>=13)&&Math.random()<clamp(.28+(game.overall-79)*.07,0,0.78)){h.push('金童奖');game.awardFlags.goldenBoy=true}if(game.age<=23&&game.overall>=80&&(ga>=18||cleanSheets>=12)&&Math.random()<.5)h.push(awards.young);
 if(['attack','wing'].includes(group)&&goals>=Math.max(20,apps*.55))h.push(awards.scorer);if(['midfield','wing'].includes(group)&&assists>=14)h.push(awards.creator);if(group==='keeper'&&cleanSheets>=Math.max(13,apps*.34))h.push(awards.keeper);if(awards.localScorer&&game.nationality==='西班牙'&&goals>=18)h.push(awards.localScorer);
 if(club.league==='意甲'&&rating>=7.15){const positional=group==='keeper'?awards.keeper:group==='defense'?awards.defender:group==='midfield'?awards.midfielder:awards.forward;if(positional&&!h.includes(positional)&&Math.random()<.56)h.push(positional)}
 const eliteOutput=group==='keeper'?cleanSheets>=15&&rating>=7.1:ga>=24&&rating>=7.05;if(game.overall>=86&&eliteOutput&&Math.random()<clamp(.22+(rating-7)*.35,0.18,.75))h.push(awards.player);if(game.overall>=88&&eliteOutput){const clasicoBonus=['皇家马德里','巴塞罗那'].includes(club.name)?16:0;const eliteBonus=['曼城','利物浦','拜仁','巴黎圣日耳曼'].includes(club.name)?5:0;const majorTitle=teamHonors.some(x=>['欧冠冠军','解放者杯冠军','世俱杯冠军'].includes(x));const production=group==='keeper'?cleanSheets-12:ga-24;const chance=clamp(2+(game.overall-88)*5.5+production*.55+(majorTitle?17:0)+clasicoBonus+eliteBonus,1,72);if(Math.random()*100<chance)h.push('金球奖')}return[...new Set(h)]
}
function nationalCompetition(nation,year){
 if(game.finalissimaYear===year&&['EU','SA'].includes(nation.confed))return'欧美杯';if(year%4===2)return'世界杯';if(nation.confed==='EU'&&year%4===0)return'欧洲杯';if(nation.confed==='SA'&&year%4===0)return'美洲杯';if(nation.confed==='AS'&&(year-2027)%4===0)return'亚洲杯';if(nation.confed==='AF'&&year%2===1)return'非洲杯';if(nation.confed==='EU'&&year%2===1)return'欧国联';return''
}
function rollNationalSeason(){
 const nation=NATIONS[game.nationality]||NATIONS.中国;const year=game.year+1;const competition=nationalCompetition(nation,year);const threshold=72+(nation.strength-65)*.35;const called=game.overall>=threshold||game.reputation>=threshold-42;if(!called)return{called:false,competition:'',apps:0,goals:0,assists:0,cleanSheets:0,saves:0,tackles:0,honors:[],stage:''};let won=false,stage='',qualified=true;if(competition==='世界杯'){const qualifyChance=clamp(18+(nation.strength-60)*3.6,22,99);qualified=Math.random()*100<qualifyChance;if(!qualified)stage='未晋级世界杯正赛'}if(competition&&qualified){const normalized=clamp((nation.strength-60)/32,0,1);let chance=Math.pow(normalized,4)*17;const playerCarry=game.overall>=91?Math.pow(game.overall-90,2)*.03*clamp((nation.strength-55)/25,.25,1):0;if(competition!=='世界杯')chance=chance*1.35+1.2;if(competition==='欧美杯')chance=clamp(20+(nation.strength-80)*2+(game.overall-85)*1.2,5,70);chance=clamp(chance+playerCarry,.001,55);won=Math.random()*100<chance;if(!won&&competition!=='欧美杯'){const deepBase=Math.pow(normalized,2.6)*56+Math.max(0,game.overall-88)*.7;if(Math.random()*100<clamp(deepBase,.08,72)){const r=Math.random();stage=r<.18?'亚军':r<.48?'四强':'八强'}}}const max=COMPETITION_MAX[competition];const stageApps=stage==='亚军'?max:stage==='四强'?max-1:stage==='八强'?max-2:!qualified?rint(2,5):rint(2,Math.max(3,(max||6)-3));const apps=competition?(competition==='欧美杯'?1:won?max:stageApps):rint(2,6);const pos=POS_STATS[game.position],group=pos.group;const goals=Math.max(0,Math.round(apps*pos.goal*.86*rand(.5,1.2)));const assists=Math.max(0,Math.round(apps*pos.assist*.82*rand(.5,1.2)));const cleanSheets=['defense','keeper'].includes(group)?Math.round(apps*clamp(.16+(nation.strength-65)*.008,.12,.48)*rand(.75,1.16)):0;const saves=group==='keeper'?Math.round(apps*rand(2.4,4.8)):0;const tackles=group==='defense'?Math.round(apps*rand(2.1,4.4)):0;game.totalNationalApps+=apps;game.totalNationalGoals+=goals;const honors=[];if(won){honors.push(`${competition}冠军`);if(['欧洲杯','美洲杯'].includes(competition))game.finalissimaYear=year+1;if(competition==='欧美杯')game.finalissimaYear=null}const reportedCompetition=competition==='世界杯'&&!qualified?'世界杯预选赛':competition;return{called:true,competition:reportedCompetition,apps,goals,assists,cleanSheets,saves,tackles,honors,stage,qualified}
}

function trophyKind(name){if(name==='世界杯冠军')return'world';if(name==='欧洲杯冠军')return'euro';if(name==='美洲杯冠军')return'copa';if(name==='亚洲杯冠军')return'asia';if(name==='非洲杯冠军')return'africa';if(['欧国联冠军','欧美杯冠军'].includes(name))return'national';if(name==='欧冠冠军')return'champions';if(name==='欧联杯冠军')return'europa';if(name==='欧协联冠军')return'conference';if(name.includes('解放者杯'))return'libertadores';if(name==='世俱杯冠军')return'club-world';if(name.includes('超级杯')||name.includes('社区盾')||name.includes('克鲁伊夫盾'))return'super';if(name.includes('金球'))return'ball';if(name.includes('金童')||name.includes('年轻')||name.includes('新人')||name.includes('U23'))return'young';if(name.includes('金靴')||name.includes('皮奇奇')||name.includes('萨拉奖')||name.includes('最佳射手'))return'boot';if(name.includes('门将')||name.includes('金手套')||name.includes('萨莫拉'))return'glove';if(name.includes('助攻王')||name.includes('最佳球员')||name.includes('MVP')||name.includes('足球先生'))return'personal';const leagues=[...new Set(CLUBS.map(c=>c.league)),...Object.values(LEAGUE_SYSTEMS)];if(leagues.some(l=>name===`${l}冠军`))return'league';return'cup'}
function trophyIcon(kind){const paths={world:'<circle cx="16" cy="7" r="4.5"/><path d="m13 10-3 4 3 4-1 5h8l-1-5 3-4-3-4m-7 13h8m-10 4h12M16 3v8m-4-5 8 2"/>',euro:'<path d="M10 4h12v12c0 4-2 6-6 6s-6-2-6-6V4Zm0 4H6v7c0 3 2 5 5 5m11-12h4v7c0 3-2 5-5 5M12 27h8m-4-5v5"/>',copa:'<path d="M12 3h8l1 5-2 3 3 10H10l3-10-2-3 1-5Zm-1 18h10m-8 0-2 6h10l-2-6"/>',asia:'<circle cx="16" cy="7" r="4"/><path d="M12 11h8l3 8-4 3h-6l-4-3 3-8Zm1 11-1 5h8l-1-5"/>',africa:'<path d="M13 3h6l2 9-3 5 3 10H11l3-10-3-5 2-9Zm-1 9h8"/>',national:'<path d="M9 5h14l-2 10c-.7 4-2.5 6-5 6s-4.3-2-5-6L9 5Zm2 4H6c0 4 2 7 6 8m9-8h5c0 4-2 7-6 8M12 27h8m-4-6v6"/>',champions:'<path d="M10 4h12v7c0 6-2 10-6 10s-6-4-6-10V4Zm0 3H5c0 5 2 8 6 9m11-9h5c0 5-2 8-6 9M12 27h8m-4-6v6"/>',europa:'<path d="M11 3h10l-2 7 3 5-4 8h-4l-4-8 3-5-2-7Zm3 20-2 4h8l-2-4M13 8h6"/>',conference:'<path d="m10 3 12 2-2 6 2 6-5 7h-2l-5-7 2-6-2-8Zm2 8h8m-7 12-2 4h10l-2-4"/>',libertadores:'<circle cx="16" cy="6" r="3"/><path d="M14 9h4v9h-4zM11 12h3m4 0h3m-9 6h8l2 5H10l2-5Zm1 5-2 4h10l-2-4"/>','club-world':'<circle cx="16" cy="10" r="7"/><path d="m12 5 8 10m0-10-8 10M8 10h16m-8 7v10m-5 0h10"/>',super:'<path d="M12 4h8l2 7-3 8h-6l-3-8 2-7Zm2 15-2 8h8l-2-8M10 8H6m16 0h4"/>',league:'<path d="m7 8 5 4 4-7 4 7 5-4-2 11H9L7 8Zm2 11h14M11 27h10m-5-8v8"/>',ball:'<circle cx="16" cy="12" r="8"/><path d="m16 7 3 2-1 4h-4l-1-4 3-2Zm-3 6-3 2m8-2 3 2M11 27h10m-5-7v7"/>',young:'<path d="M16 4c4 0 7 3 7 7 0 3-2 6-5 7v5h3v4H11v-4h3v-5c-3-1-5-4-5-7 0-4 3-7 7-7Zm-3 7h6m-3-3v6"/>',boot:'<path d="M8 7h8v9l4 3h6v5c-5 3-15 3-20 0l2-7V7Zm8 9H8m3 3 3 3m3-2 2 3"/>',glove:'<path d="M9 15V8c0-2 3-2 3 0v5-7c0-2 3-2 3 0v7-8c0-2 3-2 3 0v8-6c0-2 3-2 3 0v9l3-2c2-1 3 2 1 4l-5 7H11l-5-7c-1-2 1-4 3-3Z"/>',personal:'<path d="M10 5h12v7c0 5-2.5 8-6 8s-6-3-6-8V5Zm2 22h8m-4-7v7M10 8H6v3c0 3 2 5 5 5m11-8h4v3c0 3-2 5-5 5"/>',cup:'<path d="M11 5h10l2 5-3 9h-8l-3-9 2-5Zm-2 4H5c0 5 2 8 7 9m11-9h4c0 5-2 8-7 9M11 27h10m-5-8v8"/>'};return `<svg viewBox="0 0 32 32" aria-hidden="true">${paths[kind]||paths.cup}</svg>`}
function honorHTML(name,className='honor',count=1){const kind=trophyKind(name);return `<span class="${className}" data-trophy="${kind}">${trophyIcon(kind)}<span>${name}${count>1?` ×${count}`:''}</span></span>`}

function showReport(r){
 $('#report-year').textContent=r.season;$('#report-kicker').textContent='SEASON COMPLETE';$('#report-title').textContent=`${r.club.name} · ${r.rating}`;const notes=[];if(r.injury)notes.push(`伤病：${r.injury}`);if(r.national?.called)notes.push(nationalStatLine(r.national));if(r.leagueMovement)notes.push(r.leagueMovement.label);if(r.clubEvent)notes.push(r.clubEvent);const summary=$('#report-summary');summary.textContent=notes.join(' · ');summary.hidden=!notes.length;
 const keeper=POS_STATS[game.position].group==='keeper';$('#report-stats').innerHTML=keeper?`<div><span>能力值</span><b>${r.overall} <small>${r.overallChange>=0?'+':''}${r.overallChange}</small></b></div><div><span>出场</span><b>${r.apps}</b></div><div><span>零封</span><b>${r.cleanSheets}</b></div><div><span>扑救</span><b>${r.saves}</b></div>`:`<div><span>能力值</span><b>${r.overall} <small>${r.overallChange>=0?'+':''}${r.overallChange}</small></b></div><div><span>出场</span><b>${r.apps}</b></div><div><span>进球</span><b>${r.goals}</b></div><div><span>助攻</span><b>${r.assists}</b></div>`;
 const outcomes=[...(r.seasonStages||[]).map(x=>({text:x,kind:'stage'})),...(r.milestones||[]).map(x=>({text:x,kind:'milestone'}))];if(r.leagueMovement?.type==='relegated')outcomes.unshift({text:`降级警报 · ${r.leagueMovement.from} → ${r.leagueMovement.to}`,kind:'warning'});if(r.kickerRating)outcomes.unshift({text:`《踢球者》赛季均分 ${r.kickerRating}（1.0最佳）`,kind:'kicker'});$('#report-outcomes').innerHTML=outcomes.map(x=>`<span class="outcome-tag ${x.kind}">${x.text}</span>`).join('');const honors=[...r.teamHonors,...r.personal,...r.nationalHonors];$('#report-honors').innerHTML=honors.map(x=>honorHTML(x)).join('');$('#report').hidden=false;
}
function nationalStatLine(n){const group=POS_STATS[game.position].group;const head=`${game.nationality}${n.competition?` · ${n.competition}${n.honors.length?'冠军':n.stage?` · ${n.stage}`:''}`:''}`;if(group==='keeper')return`${head} · ${n.apps}场 · ${n.cleanSheets}零封 · ${n.saves}扑救`;if(group==='defense')return`${head} · ${n.apps}场 · ${n.cleanSheets}零封 · ${n.tackles}次抢断`;return`${head} · ${n.apps}场 · ${n.goals}球 · ${n.assists}助`}
function nextSeason(){
 $('#report').hidden=true;game.age++;game.year++;game.season++;if(game.parentClub){game.club={...game.parentClub};game.parentClub=null}if(game.age>=38){retire();return}evolveClubPowers();renderGame()
}
function careerEvaluation(allHonors){
 const counts=allHonors.reduce((a,h)=>(a[h]=(a[h]||0)+1,a),{}),records=game.history||[],ballons=counts.金球奖||0,world=counts.世界杯冠军||0;
 const clubMajors=(counts.欧冠冠军||0)+(counts.解放者杯冠军||0)+(counts.亚冠精英联赛冠军||0)+(counts.中北美冠军杯冠军||0)+(counts.世俱杯冠军||0),nationalMajors=world+(counts.欧洲杯冠军||0)+(counts.美洲杯冠军||0)+(counts.亚洲杯冠军||0)+(counts.非洲杯冠军||0),major=clubMajors+nationalMajors;
 const peak=Math.max(game.overall||0,...records.map(r=>r.overall||0)),topSeasons=records.filter(r=>(r.overall||0)>=85).length,eliteSeasons=records.filter(r=>(r.overall||0)>=88).length,worldSeasons=records.filter(r=>(r.overall||0)>=91).length,leagueBest=allHonors.filter(h=>/(赛季最佳球员|年度最佳球员|足球先生|MVP|最有价值球员|比利时金靴奖)/.test(h)).length,group=POS_STATS[game.position].group;
 const production=group==='keeper'?(game.totalCleanSheets||0)/18+(game.totalSaves||0)/550:group==='defense'?(game.totalGoals||0)/40+(game.totalAssists||0)/35+(game.totalApps||0)/90:group==='midfield'?(game.totalGoals||0)/35+(game.totalAssists||0)/30+(game.totalApps||0)/110:(game.totalGoals||0)/35+(game.totalAssists||0)/45;
 const score=(game.totalApps||0)/45+(game.totalNationalApps||0)/13+clamp((peak-72)*1.6,0,36)+topSeasons*.55+eliteSeasons*.75+worldSeasons*1.4+clamp(production,0,18)+ballons*10+world*14+(clubMajors-(counts.世俱杯冠军||0))*5+(counts.世俱杯冠军||0)*2+(nationalMajors-world)*7+leagueBest*1.5+(game.reputation||0)*.06;
 let historical=records.length?'国脚级':'小区级';
 if(score>=32&&(peak>=78||game.totalNationalApps>=20))historical='洲际级';
 if(score>=55&&peak>=85&&topSeasons>=3)historical='世界级';
 if(score>=75&&peak>=88&&eliteSeasons>=3&&(major>=1||leagueBest>=3))historical='历史级';
 if(score>=95&&peak>=90&&eliteSeasons>=5&&(ballons>=1||major>=3||leagueBest>=6))historical='殿堂级';
 if(score>=125&&peak>=92&&worldSeasons>=5&&ballons>=1&&major>=3)historical='准球王级';
 if(score>=155&&peak>=94&&worldSeasons>=7&&ballons>=4&&world>=1&&major>=5)historical='球王级';
 const clubRows={};records.forEach(r=>{const row=clubRows[r.club.name]||(clubRows[r.club.name]={apps:0,goals:0,assists:0,trophies:0});row.apps+=r.apps;row.goals+=r.goals;row.assists+=r.assists;row.trophies+=(r.teamHonors||[]).length});const [clubName,row]=Object.entries(clubRows).sort((a,b)=>b[1].apps-a[1].apps)[0]||['—',{apps:0,goals:0,assists:0,trophies:0}];let clubStatus='短期效力';if(row.apps>=500&&row.trophies>=12&&(row.goals+row.assists)>=220)clubStatus='队史最佳之一';else if(row.apps>=350&&row.trophies>=8)clubStatus='俱乐部传奇';else if(row.apps>=250&&row.trophies>=4)clubStatus='俱乐部名宿';else if(row.apps>=150)clubStatus='长期主力';else if(row.apps>=60)clubStatus='一线队成员';return{historical,club:`${clubName} · ${clubStatus}`,ballons,major,score:Math.round(score)}
}
function retire(){game.retired=true;const allHonors=game.history.flatMap(r=>[...(r.teamHonors||[]),...(r.personal||[]),...(r.nationalHonors||[])]),evaluation=careerEvaluation(allHonors),keeper=POS_STATS[game.position].group==='keeper';$('#report').hidden=false;$('#report-year').textContent=`${game.year}`;$('#report-kicker').textContent='CAREER COMPLETE';$('#report-title').textContent=`历史地位 · ${evaluation.historical}`;const summary=$('#report-summary');summary.hidden=false;summary.textContent=keeper?`俱乐部 ${game.totalApps} 场 · ${game.totalCleanSheets} 零封 · ${game.totalSaves} 扑救 · 国家队 ${game.totalNationalApps} 场`:`俱乐部 ${game.totalApps} 场 · ${game.totalGoals} 球 · ${game.totalAssists} 助 · 国家队 ${game.totalNationalApps} 场 ${game.totalNationalGoals} 球`;$('#report-stats').innerHTML=`<div><span>最终能力</span><b>${game.overall}</b></div><div><span>出场</span><b>${game.totalApps}</b></div><div><span>冠军</span><b>${game.trophyCount}</b></div><div><span>金球奖</span><b>${evaluation.ballons}</b></div>`;$('#report-outcomes').innerHTML=`<span class="outcome-tag milestone">足坛地位 · ${evaluation.historical}</span><span class="outcome-tag stage">俱乐部地位 · ${evaluation.club}</span>`;$('#report-honors').innerHTML=[...new Set(allHonors)].map(x=>honorHTML(x)).join('');$('#next-season').textContent='查看完整履历';$('#next-season').onclick=()=>{$('#report').hidden=true};save()}
function renderTimeline(){
 const spells=groupCareerSpells();$('#timeline').innerHTML=spells.length?spells.map(spell=>`<section class="career-spell"><header><b>${spell.club.name}</b><small>${spell.club.league} · ${spell.records.length} 个赛季</small></header>${spell.records.map(r=>{const honors=[...(r.teamHonors||[]),...(r.personal||[]),...(r.nationalHonors||[])];const stats=game.position==='GK'?`${r.apps} 场 · ${r.cleanSheets||0} 零封 · ${r.saves||0} 扑救`:`${r.apps} 场 · ${r.goals} 球 · ${r.assists} 助`;return`<article class="year-row spell-season"><span>${r.season}</span><div class="year-club"><small>${r.moveType?`${r.moveType}${r.transferFee?` ${formatMoney(r.transferFee)}`:''} · `:''}实力 ${r.clubPower||r.club.power} · ${r.role} · ${r.plan}${r.leagueMovement?` · ${r.leagueMovement.label}`:''}${r.injury?` · ${r.injury}`:''}</small></div><div class="year-result"><b>${stats}</b><small>${honors.join(' · ')}</small></div><strong class="year-ovr">${r.overall}<small>${(r.overallChange||0)>=0?'+':''}${r.overallChange||0}</small></strong></article>`}).join('')}</section>`).join(''):'<p class="empty">第一份职业合同还没有签字。</p>'
}
function groupCareerSpells(){const spells=[];game.history.forEach(record=>{const current=spells.at(-1);if(current&&current.club.name===record.club.name)current.records.push(record);else spells.push({club:record.club,records:[record]})});return spells}
function renderHonorCabinet(){
 const honors=game.history.flatMap(r=>[...(r.teamHonors||[]),...(r.personal||[]),...(r.nationalHonors||[])]);const counts=honors.reduce((all,h)=>{all[h]=(all[h]||0)+1;return all},{});$('#total-honor-count').textContent=honors.length;$('#honor-count').textContent=`${honors.length} 项荣誉`;$('#career-honors').innerHTML=honors.length?Object.entries(counts).map(([name,count])=>honorHTML(name,'career-honor',count)).join(''):'<small>荣誉室还是空的</small>'
}

$('#setup-form').onsubmit=e=>{e.preventDefault();const nationality=$('#nationality').value;const name=composePlayerName($('#player-family-name').value,$('#player-given-name').value,nationality);const position=document.querySelector('input[name="position"]:checked').value;game=newGame(name,position,nationality,+$('#start-age').value,+$('#shirt-number').value||0);renderGame()};
$('#simulate').onclick=simulateSeason;$('#next-season').onclick=nextSeason;$('#retire-early').onclick=()=>{if(confirm('确定现在退役，并生成完整生涯报告？'))retire()};$('#reset').onclick=()=>{if(confirm('确定删除当前生涯并重新开档？')){localStorage.removeItem(SAVE_KEY);location.reload()}};
$('#lock-nationality').onclick=()=>{game.nationality=$('#passport-nationality').value;game.needsNationality=false;renderGame()};
const existing=load();if(existing){$('#continue').hidden=false;$('#continue').onclick=()=>{game=existing;renderGame()}}
